/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const AnimalType = IDL.Variant({
  'Fox' : IDL.Null,
  'Owl' : IDL.Null,
  'Sheep' : IDL.Null,
  'Elephant' : IDL.Null,
  'Bear' : IDL.Null,
  'Lion' : IDL.Null,
  'Wolf' : IDL.Null,
  'Shepherd' : IDL.Null,
  'GoldenRetriever' : IDL.Null,
  'Otter' : IDL.Null,
  'Beaver' : IDL.Null,
  'Dolphin' : IDL.Null,
});
export const AnimalResultEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : IDL.Int,
  'score' : IDL.Nat,
  'animalType' : AnimalType,
});
export const EmotionResultEntry = IDL.Record({
  'id' : IDL.Nat,
  'emotionType' : IDL.Text,
  'userId' : UserId,
  'createdAt' : IDL.Int,
  'score' : IDL.Float64,
});
export const ResultCounts = IDL.Record({
  'darkSideResults' : IDL.Nat,
  'emotionResults' : IDL.Nat,
  'animalResults' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const SevenSinsResultEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'envy' : IDL.Float64,
  'dominantSin' : IDL.Text,
  'lust' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'gluttony' : IDL.Float64,
  'sloth' : IDL.Float64,
  'greed' : IDL.Float64,
  'pride' : IDL.Float64,
  'wrath' : IDL.Float64,
});
export const DarkSideResultEntry = IDL.Record({
  'id' : IDL.Nat,
  'fullResultJson' : IDL.Text,
  'userId' : UserId,
  'createdAt' : IDL.Int,
  'personalityType' : IDL.Text,
  'dominantPercentage' : IDL.Float64,
});
export const UserResultsAdmin = IDL.Record({
  'emotion' : IDL.Vec(EmotionResultEntry),
  'animal' : IDL.Vec(AnimalResultEntry),
  'darkSide' : IDL.Vec(DarkSideResultEntry),
});
export const AppAnalytics = IDL.Record({
  'animalResultsCount' : IDL.Nat,
  'totalEmotionResults' : IDL.Nat,
  'darkSideResultsCount' : IDL.Nat,
  'totalFeedback' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'emotionResultsCount' : IDL.Nat,
  'totalAnimalResults' : IDL.Nat,
});
export const AdminConfig = IDL.Record({
  'adminPrincipal' : IDL.Text,
  'isDraftMode' : IDL.Bool,
});
export const DarkSideType = IDL.Variant({
  'Manipulator' : IDL.Null,
  'Sociopath' : IDL.Null,
  'IntrovertedThinker' : IDL.Null,
  'Psychopath' : IDL.Null,
  'ExtravertedThinker' : IDL.Null,
  'ExtravertedFeeler' : IDL.Null,
  'IntrovertedFeeler' : IDL.Null,
});
export const DarkSideScore = IDL.Record({
  'count' : IDL.Nat,
  'darkType' : DarkSideType,
  'percentage' : IDL.Float64,
});
export const DarkSideResultSummary = IDL.Record({
  'topTypes' : IDL.Vec(DarkSideScore),
  'takenAt' : IDL.Int,
});
export const EmotionType = IDL.Variant({
  'Awe' : IDL.Null,
  'Sadness' : IDL.Null,
  'Fear' : IDL.Null,
  'Guilt' : IDL.Null,
  'Love' : IDL.Null,
  'Peace' : IDL.Null,
  'Desire' : IDL.Null,
  'Anger' : IDL.Null,
  'Happiness' : IDL.Null,
  'Anxiety' : IDL.Null,
});
export const EmotionScore = IDL.Record({
  'emotion' : EmotionType,
  'count' : IDL.Nat,
  'percentage' : IDL.Float64,
});
export const EmotionResultSummary = IDL.Record({
  'takenAt' : IDL.Int,
  'topEmotions' : IDL.Vec(EmotionScore),
});
export const UserAccount = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'darkSideResult' : IDL.Opt(DarkSideResultSummary),
  'gender' : IDL.Text,
  'lastLogin' : IDL.Int,
  'animalArchetype' : IDL.Opt(AnimalType),
  'securityQuestionUpdatedAt' : IDL.Opt(IDL.Int),
  'emotionResult' : IDL.Opt(EmotionResultSummary),
});
export const UserId__1 = IDL.Principal;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'userId' : UserId__1,
  'takenAt' : Timestamp,
  'archetype' : AnimalType,
});
export const UserAccountAdmin = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'darkSideResult' : IDL.Opt(DarkSideResultSummary),
  'gender' : IDL.Text,
  'passwordHash' : IDL.Text,
  'lastLogin' : IDL.Int,
  'animalArchetype' : IDL.Opt(AnimalType),
  'emotionResult' : IDL.Opt(EmotionResultSummary),
});
export const FeedbackEntry = IDL.Record({
  'id' : IDL.Text,
  'userEmail' : IDL.Text,
  'feedback' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SessionToken = IDL.Record({
  'token' : IDL.Text,
  'expiresAt' : IDL.Int,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminGetAllAnimalResults' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(AnimalResultEntry), 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllEmotionResults' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(EmotionResultEntry), 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllResultCounts' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : ResultCounts, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllSevenSinsResults' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(SevenSinsResultEntry), 'err' : IDL.Text })],
      [],
    ),
  'adminGetUserResults' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserResultsAdmin, 'err' : IDL.Text })],
      [],
    ),
  'claimAdmin' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createAccount' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteFeedbackEntry' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAnalytics' : IDL.Func([], [AppAnalytics], []),
  'getAppConfig' : IDL.Func([], [AdminConfig], ['query']),
  'getDarkSideResult' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Opt(DarkSideResultSummary),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getMyAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserAccount, 'err' : IDL.Text })],
      [],
    ),
  'getMyAnimalResults' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(AnimalResultEntry), 'err' : IDL.Text })],
      [],
    ),
  'getMyDarkSideResults' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(DarkSideResultEntry), 'err' : IDL.Text })],
      [],
    ),
  'getMyEmotionResults' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(EmotionResultEntry), 'err' : IDL.Text })],
      [],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMySevenSinsResults' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(SevenSinsResultEntry), 'err' : IDL.Text })],
      [],
    ),
  'getSecurityHint' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getSecurityQuestion' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getSecurityQuestionUpdatedAt' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Opt(IDL.Int), 'err' : IDL.Text })],
      [],
    ),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserAccountAdmin)], []),
  'listFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], []),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text })],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'resetPasswordWithSecurityQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveAnimalResult' : IDL.Func(
      [IDL.Text, AnimalType, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveDarkSideResult' : IDL.Func(
      [IDL.Text, IDL.Vec(DarkSideScore)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveDarkSideResultEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveEmotionResult' : IDL.Func(
      [IDL.Text, IDL.Vec(EmotionScore)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveEmotionResultEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveMyProfile' : IDL.Func([AnimalType], [], []),
  'saveSevenSinsResult' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'setDraftMode' : IDL.Func(
      [IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'submitFeedback' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateSecurityQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'verifySecurityQuestion' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const AnimalType = IDL.Variant({
    'Fox' : IDL.Null,
    'Owl' : IDL.Null,
    'Sheep' : IDL.Null,
    'Elephant' : IDL.Null,
    'Bear' : IDL.Null,
    'Lion' : IDL.Null,
    'Wolf' : IDL.Null,
    'Shepherd' : IDL.Null,
    'GoldenRetriever' : IDL.Null,
    'Otter' : IDL.Null,
    'Beaver' : IDL.Null,
    'Dolphin' : IDL.Null,
  });
  const AnimalResultEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : IDL.Int,
    'score' : IDL.Nat,
    'animalType' : AnimalType,
  });
  const EmotionResultEntry = IDL.Record({
    'id' : IDL.Nat,
    'emotionType' : IDL.Text,
    'userId' : UserId,
    'createdAt' : IDL.Int,
    'score' : IDL.Float64,
  });
  const ResultCounts = IDL.Record({
    'darkSideResults' : IDL.Nat,
    'emotionResults' : IDL.Nat,
    'animalResults' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const SevenSinsResultEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'envy' : IDL.Float64,
    'dominantSin' : IDL.Text,
    'lust' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'gluttony' : IDL.Float64,
    'sloth' : IDL.Float64,
    'greed' : IDL.Float64,
    'pride' : IDL.Float64,
    'wrath' : IDL.Float64,
  });
  const DarkSideResultEntry = IDL.Record({
    'id' : IDL.Nat,
    'fullResultJson' : IDL.Text,
    'userId' : UserId,
    'createdAt' : IDL.Int,
    'personalityType' : IDL.Text,
    'dominantPercentage' : IDL.Float64,
  });
  const UserResultsAdmin = IDL.Record({
    'emotion' : IDL.Vec(EmotionResultEntry),
    'animal' : IDL.Vec(AnimalResultEntry),
    'darkSide' : IDL.Vec(DarkSideResultEntry),
  });
  const AppAnalytics = IDL.Record({
    'animalResultsCount' : IDL.Nat,
    'totalEmotionResults' : IDL.Nat,
    'darkSideResultsCount' : IDL.Nat,
    'totalFeedback' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'emotionResultsCount' : IDL.Nat,
    'totalAnimalResults' : IDL.Nat,
  });
  const AdminConfig = IDL.Record({
    'adminPrincipal' : IDL.Text,
    'isDraftMode' : IDL.Bool,
  });
  const DarkSideType = IDL.Variant({
    'Manipulator' : IDL.Null,
    'Sociopath' : IDL.Null,
    'IntrovertedThinker' : IDL.Null,
    'Psychopath' : IDL.Null,
    'ExtravertedThinker' : IDL.Null,
    'ExtravertedFeeler' : IDL.Null,
    'IntrovertedFeeler' : IDL.Null,
  });
  const DarkSideScore = IDL.Record({
    'count' : IDL.Nat,
    'darkType' : DarkSideType,
    'percentage' : IDL.Float64,
  });
  const DarkSideResultSummary = IDL.Record({
    'topTypes' : IDL.Vec(DarkSideScore),
    'takenAt' : IDL.Int,
  });
  const EmotionType = IDL.Variant({
    'Awe' : IDL.Null,
    'Sadness' : IDL.Null,
    'Fear' : IDL.Null,
    'Guilt' : IDL.Null,
    'Love' : IDL.Null,
    'Peace' : IDL.Null,
    'Desire' : IDL.Null,
    'Anger' : IDL.Null,
    'Happiness' : IDL.Null,
    'Anxiety' : IDL.Null,
  });
  const EmotionScore = IDL.Record({
    'emotion' : EmotionType,
    'count' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  const EmotionResultSummary = IDL.Record({
    'takenAt' : IDL.Int,
    'topEmotions' : IDL.Vec(EmotionScore),
  });
  const UserAccount = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'darkSideResult' : IDL.Opt(DarkSideResultSummary),
    'gender' : IDL.Text,
    'lastLogin' : IDL.Int,
    'animalArchetype' : IDL.Opt(AnimalType),
    'securityQuestionUpdatedAt' : IDL.Opt(IDL.Int),
    'emotionResult' : IDL.Opt(EmotionResultSummary),
  });
  const UserId__1 = IDL.Principal;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'userId' : UserId__1,
    'takenAt' : Timestamp,
    'archetype' : AnimalType,
  });
  const UserAccountAdmin = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'darkSideResult' : IDL.Opt(DarkSideResultSummary),
    'gender' : IDL.Text,
    'passwordHash' : IDL.Text,
    'lastLogin' : IDL.Int,
    'animalArchetype' : IDL.Opt(AnimalType),
    'emotionResult' : IDL.Opt(EmotionResultSummary),
  });
  const FeedbackEntry = IDL.Record({
    'id' : IDL.Text,
    'userEmail' : IDL.Text,
    'feedback' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SessionToken = IDL.Record({
    'token' : IDL.Text,
    'expiresAt' : IDL.Int,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'adminGetAllAnimalResults' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(AnimalResultEntry), 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllEmotionResults' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(EmotionResultEntry), 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllResultCounts' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : ResultCounts, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllSevenSinsResults' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Vec(SevenSinsResultEntry),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'adminGetUserResults' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserResultsAdmin, 'err' : IDL.Text })],
        [],
      ),
    'claimAdmin' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createAccount' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteFeedbackEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAnalytics' : IDL.Func([], [AppAnalytics], []),
    'getAppConfig' : IDL.Func([], [AdminConfig], ['query']),
    'getDarkSideResult' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Opt(DarkSideResultSummary),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getMyAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserAccount, 'err' : IDL.Text })],
        [],
      ),
    'getMyAnimalResults' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(AnimalResultEntry), 'err' : IDL.Text })],
        [],
      ),
    'getMyDarkSideResults' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(DarkSideResultEntry),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getMyEmotionResults' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(EmotionResultEntry), 'err' : IDL.Text })],
        [],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMySevenSinsResults' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(SevenSinsResultEntry),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getSecurityHint' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getSecurityQuestion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getSecurityQuestionUpdatedAt' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Opt(IDL.Int), 'err' : IDL.Text })],
        [],
      ),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserAccountAdmin)], []),
    'listFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], []),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text })],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'resetPasswordWithSecurityQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveAnimalResult' : IDL.Func(
        [IDL.Text, AnimalType, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveDarkSideResult' : IDL.Func(
        [IDL.Text, IDL.Vec(DarkSideScore)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveDarkSideResultEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveEmotionResult' : IDL.Func(
        [IDL.Text, IDL.Vec(EmotionScore)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveEmotionResultEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveMyProfile' : IDL.Func([AnimalType], [], []),
    'saveSevenSinsResult' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'setDraftMode' : IDL.Func(
        [IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'submitFeedback' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateSecurityQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'verifySecurityQuestion' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };