/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfig {
  'adminPrincipal' : string,
  'isDraftMode' : boolean,
}
export interface AnimalResultEntry {
  'id' : bigint,
  'userId' : UserId,
  'createdAt' : bigint,
  'score' : bigint,
  'animalType' : AnimalType,
}
export type AnimalType = { 'Fox' : null } |
  { 'Owl' : null } |
  { 'Sheep' : null } |
  { 'Elephant' : null } |
  { 'Bear' : null } |
  { 'Lion' : null } |
  { 'Wolf' : null } |
  { 'Shepherd' : null } |
  { 'GoldenRetriever' : null } |
  { 'Otter' : null } |
  { 'Beaver' : null } |
  { 'Dolphin' : null };
export interface AppAnalytics {
  'animalResultsCount' : bigint,
  'totalEmotionResults' : bigint,
  'darkSideResultsCount' : bigint,
  'totalFeedback' : bigint,
  'totalUsers' : bigint,
  'emotionResultsCount' : bigint,
  'totalAnimalResults' : bigint,
}
export interface DarkSideResultEntry {
  'id' : bigint,
  'fullResultJson' : string,
  'userId' : UserId,
  'createdAt' : bigint,
  'personalityType' : string,
  'dominantPercentage' : number,
}
export interface DarkSideResultSummary {
  'topTypes' : Array<DarkSideScore>,
  'takenAt' : bigint,
}
export interface DarkSideScore {
  'count' : bigint,
  'darkType' : DarkSideType,
  'percentage' : number,
}
export type DarkSideType = { 'Manipulator' : null } |
  { 'Sociopath' : null } |
  { 'IntrovertedThinker' : null } |
  { 'Psychopath' : null } |
  { 'ExtravertedThinker' : null } |
  { 'ExtravertedFeeler' : null } |
  { 'IntrovertedFeeler' : null };
export interface EmotionResultEntry {
  'id' : bigint,
  'emotionType' : string,
  'userId' : UserId,
  'createdAt' : bigint,
  'score' : number,
}
export interface EmotionResultSummary {
  'takenAt' : bigint,
  'topEmotions' : Array<EmotionScore>,
}
export interface EmotionScore {
  'emotion' : EmotionType,
  'count' : bigint,
  'percentage' : number,
}
export type EmotionType = { 'Awe' : null } |
  { 'Sadness' : null } |
  { 'Fear' : null } |
  { 'Guilt' : null } |
  { 'Love' : null } |
  { 'Peace' : null } |
  { 'Desire' : null } |
  { 'Anger' : null } |
  { 'Happiness' : null } |
  { 'Anxiety' : null };
export interface FeedbackEntry {
  'id' : string,
  'userEmail' : string,
  'feedback' : string,
  'timestamp' : bigint,
}
export interface ResultCounts {
  'darkSideResults' : bigint,
  'emotionResults' : bigint,
  'animalResults' : bigint,
  'totalUsers' : bigint,
}
export interface SessionToken {
  'token' : string,
  'expiresAt' : bigint,
  'email' : string,
}
export interface SevenSinsResultEntry {
  'id' : bigint,
  'userId' : UserId,
  'envy' : number,
  'dominantSin' : string,
  'lust' : number,
  'name' : string,
  'createdAt' : bigint,
  'gluttony' : number,
  'sloth' : number,
  'greed' : number,
  'pride' : number,
  'wrath' : number,
}
export type Timestamp = bigint;
export interface UserAccount {
  'id' : string,
  'age' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'darkSideResult' : [] | [DarkSideResultSummary],
  'gender' : string,
  'lastLogin' : bigint,
  'animalArchetype' : [] | [AnimalType],
  'securityQuestionUpdatedAt' : [] | [bigint],
  'emotionResult' : [] | [EmotionResultSummary],
}
export interface UserAccountAdmin {
  'id' : string,
  'age' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'darkSideResult' : [] | [DarkSideResultSummary],
  'gender' : string,
  'passwordHash' : string,
  'lastLogin' : bigint,
  'animalArchetype' : [] | [AnimalType],
  'emotionResult' : [] | [EmotionResultSummary],
}
export type UserId = string;
export type UserId__1 = Principal;
export interface UserProfile {
  'userId' : UserId__1,
  'takenAt' : Timestamp,
  'archetype' : AnimalType,
}
export interface UserResultsAdmin {
  'emotion' : Array<EmotionResultEntry>,
  'animal' : Array<AnimalResultEntry>,
  'darkSide' : Array<DarkSideResultEntry>,
}
export interface _SERVICE {
  'adminGetAllAnimalResults' : ActorMethod<
    [],
    { 'ok' : Array<AnimalResultEntry> } |
      { 'err' : string }
  >,
  'adminGetAllEmotionResults' : ActorMethod<
    [],
    { 'ok' : Array<EmotionResultEntry> } |
      { 'err' : string }
  >,
  'adminGetAllResultCounts' : ActorMethod<
    [],
    { 'ok' : ResultCounts } |
      { 'err' : string }
  >,
  'adminGetAllSevenSinsResults' : ActorMethod<
    [],
    { 'ok' : Array<SevenSinsResultEntry> } |
      { 'err' : string }
  >,
  'adminGetUserResults' : ActorMethod<
    [string],
    { 'ok' : UserResultsAdmin } |
      { 'err' : string }
  >,
  'claimAdmin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'createAccount' : ActorMethod<
    [string, string, string, bigint, string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteFeedbackEntry' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteUser' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'getAnalytics' : ActorMethod<[], AppAnalytics>,
  'getAppConfig' : ActorMethod<[], AdminConfig>,
  'getDarkSideResult' : ActorMethod<
    [string],
    { 'ok' : [] | [DarkSideResultSummary] } |
      { 'err' : string }
  >,
  'getMyAccount' : ActorMethod<
    [string],
    { 'ok' : UserAccount } |
      { 'err' : string }
  >,
  'getMyAnimalResults' : ActorMethod<
    [string],
    { 'ok' : Array<AnimalResultEntry> } |
      { 'err' : string }
  >,
  'getMyDarkSideResults' : ActorMethod<
    [string],
    { 'ok' : Array<DarkSideResultEntry> } |
      { 'err' : string }
  >,
  'getMyEmotionResults' : ActorMethod<
    [string],
    { 'ok' : Array<EmotionResultEntry> } |
      { 'err' : string }
  >,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMySevenSinsResults' : ActorMethod<
    [string],
    { 'ok' : Array<SevenSinsResultEntry> } |
      { 'err' : string }
  >,
  'getSecurityHint' : ActorMethod<[string], [] | [string]>,
  'getSecurityQuestion' : ActorMethod<[string], [] | [string]>,
  'getSecurityQuestionUpdatedAt' : ActorMethod<
    [string],
    { 'ok' : [] | [bigint] } |
      { 'err' : string }
  >,
  'listAllUsers' : ActorMethod<[], Array<UserAccountAdmin>>,
  'listFeedback' : ActorMethod<[], Array<FeedbackEntry>>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : SessionToken } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'resetPasswordWithSecurityQuestion' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveAnimalResult' : ActorMethod<
    [string, AnimalType, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveDarkSideResult' : ActorMethod<
    [string, Array<DarkSideScore>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveDarkSideResultEntry' : ActorMethod<
    [string, string, number, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveEmotionResult' : ActorMethod<
    [string, Array<EmotionScore>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveEmotionResultEntry' : ActorMethod<
    [string, string, number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveMyProfile' : ActorMethod<[AnimalType], undefined>,
  'saveSevenSinsResult' : ActorMethod<
    [
      string,
      string,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      string,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'setDraftMode' : ActorMethod<[boolean], { 'ok' : null } | { 'err' : string }>,
  'submitFeedback' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSecurityQuestion' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'verifySecurityQuestion' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];