/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DarkSideResultSummary {
    topTypes: Array<DarkSideScore>;
    takenAt: bigint;
}
export interface UserAccountAdmin {
    id: string;
    age: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    darkSideResult?: DarkSideResultSummary;
    gender: string;
    passwordHash: string;
    lastLogin: bigint;
    animalArchetype?: AnimalType;
    emotionResult?: EmotionResultSummary;
}
export type Timestamp = bigint;
export interface AppAnalytics {
    animalResultsCount: bigint;
    totalEmotionResults: bigint;
    darkSideResultsCount: bigint;
    totalFeedback: bigint;
    totalUsers: bigint;
    emotionResultsCount: bigint;
    totalAnimalResults: bigint;
}
export type UserId__1 = Principal;
export interface EmotionResultSummary {
    takenAt: bigint;
    topEmotions: Array<EmotionScore>;
}
export interface UserAccount {
    id: string;
    age: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    darkSideResult?: DarkSideResultSummary;
    gender: string;
    lastLogin: bigint;
    animalArchetype?: AnimalType;
    securityQuestionUpdatedAt?: bigint;
    emotionResult?: EmotionResultSummary;
}
export interface SevenSinsResultEntry {
    id: bigint;
    userId: UserId;
    envy: number;
    dominantSin: string;
    lust: number;
    name: string;
    createdAt: bigint;
    gluttony: number;
    sloth: number;
    greed: number;
    pride: number;
    wrath: number;
}
export interface ResultCounts {
    darkSideResults: bigint;
    emotionResults: bigint;
    animalResults: bigint;
    totalUsers: bigint;
}
export interface FeedbackEntry {
    id: string;
    userEmail: string;
    feedback: string;
    timestamp: bigint;
}
export interface DarkSideScore {
    count: bigint;
    darkType: DarkSideType;
    percentage: number;
}
export type UserId = string;
export interface EmotionResultEntry {
    id: bigint;
    emotionType: string;
    userId: UserId;
    createdAt: bigint;
    score: number;
}
export interface UserResultsAdmin {
    emotion: Array<EmotionResultEntry>;
    animal: Array<AnimalResultEntry>;
    darkSide: Array<DarkSideResultEntry>;
}
export interface SessionToken {
    token: string;
    expiresAt: bigint;
    email: string;
}
export interface DarkSideResultEntry {
    id: bigint;
    fullResultJson: string;
    userId: UserId;
    createdAt: bigint;
    personalityType: string;
    dominantPercentage: number;
}
export interface EmotionScore {
    emotion: EmotionType;
    count: bigint;
    percentage: number;
}
export interface AdminConfig {
    adminPrincipal: string;
    isDraftMode: boolean;
}
export interface UserProfile {
    userId: UserId__1;
    takenAt: Timestamp;
    archetype: AnimalType;
}
export interface AnimalResultEntry {
    id: bigint;
    userId: UserId;
    createdAt: bigint;
    score: bigint;
    animalType: AnimalType;
}
export enum AnimalType {
    Fox = "Fox",
    Owl = "Owl",
    Sheep = "Sheep",
    Elephant = "Elephant",
    Bear = "Bear",
    Lion = "Lion",
    Wolf = "Wolf",
    Shepherd = "Shepherd",
    GoldenRetriever = "GoldenRetriever",
    Otter = "Otter",
    Beaver = "Beaver",
    Dolphin = "Dolphin"
}
export enum DarkSideType {
    Manipulator = "Manipulator",
    Sociopath = "Sociopath",
    IntrovertedThinker = "IntrovertedThinker",
    Psychopath = "Psychopath",
    ExtravertedThinker = "ExtravertedThinker",
    ExtravertedFeeler = "ExtravertedFeeler",
    IntrovertedFeeler = "IntrovertedFeeler"
}
export enum EmotionType {
    Awe = "Awe",
    Sadness = "Sadness",
    Fear = "Fear",
    Guilt = "Guilt",
    Love = "Love",
    Peace = "Peace",
    Desire = "Desire",
    Anger = "Anger",
    Happiness = "Happiness",
    Anxiety = "Anxiety"
}
export interface backendInterface {
    adminGetAllAnimalResults(): Promise<{
        __kind__: "ok";
        ok: Array<AnimalResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllEmotionResults(): Promise<{
        __kind__: "ok";
        ok: Array<EmotionResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllResultCounts(): Promise<{
        __kind__: "ok";
        ok: ResultCounts;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllSevenSinsResults(): Promise<{
        __kind__: "ok";
        ok: Array<SevenSinsResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetUserResults(userEmail: string): Promise<{
        __kind__: "ok";
        ok: UserResultsAdmin;
    } | {
        __kind__: "err";
        err: string;
    }>;
    claimAdmin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createAccount(email: string, password: string, name: string, age: bigint, gender: string, securityQuestion: string, securityAnswer: string, securityHint: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteFeedbackEntry(id: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteUser(email: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAnalytics(): Promise<AppAnalytics>;
    getAppConfig(): Promise<AdminConfig>;
    getDarkSideResult(token: string): Promise<{
        __kind__: "ok";
        ok: DarkSideResultSummary | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyAccount(token: string): Promise<{
        __kind__: "ok";
        ok: UserAccount;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyAnimalResults(token: string): Promise<{
        __kind__: "ok";
        ok: Array<AnimalResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyDarkSideResults(token: string): Promise<{
        __kind__: "ok";
        ok: Array<DarkSideResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyEmotionResults(token: string): Promise<{
        __kind__: "ok";
        ok: Array<EmotionResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyProfile(): Promise<UserProfile | null>;
    getMySevenSinsResults(token: string): Promise<{
        __kind__: "ok";
        ok: Array<SevenSinsResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getSecurityHint(email: string): Promise<string | null>;
    getSecurityQuestion(email: string): Promise<string | null>;
    getSecurityQuestionUpdatedAt(token: string): Promise<{
        __kind__: "ok";
        ok: bigint | null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listAllUsers(): Promise<Array<UserAccountAdmin>>;
    listFeedback(): Promise<Array<FeedbackEntry>>;
    login(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: SessionToken;
    } | {
        __kind__: "err";
        err: string;
    }>;
    logout(token: string): Promise<void>;
    resetPasswordWithSecurityQuestion(email: string, question: string, answer: string, newPassword: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveAnimalResult(token: string, animalType: AnimalType, score: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveDarkSideResult(token: string, scores: Array<DarkSideScore>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveDarkSideResultEntry(token: string, personalityType: string, dominantPercentage: number, fullResultJson: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveEmotionResult(token: string, scores: Array<EmotionScore>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveEmotionResultEntry(token: string, emotionType: string, score: number): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveMyProfile(archetype: AnimalType): Promise<void>;
    saveSevenSinsResult(token: string, name: string, pride: number, greed: number, wrath: number, envy: number, gluttony: number, lust: number, sloth: number, dominantSin: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setDraftMode(isDraft: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitFeedback(feedback: string, userEmail: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateSecurityQuestion(token: string, newQuestion: string, newAnswer: string, newHint: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    verifySecurityQuestion(email: string, answer: string): Promise<boolean>;
}
import type { AnimalResultEntry as _AnimalResultEntry, AnimalType as _AnimalType, DarkSideResultEntry as _DarkSideResultEntry, DarkSideResultSummary as _DarkSideResultSummary, DarkSideScore as _DarkSideScore, DarkSideType as _DarkSideType, EmotionResultEntry as _EmotionResultEntry, EmotionResultSummary as _EmotionResultSummary, EmotionScore as _EmotionScore, EmotionType as _EmotionType, ResultCounts as _ResultCounts, SessionToken as _SessionToken, SevenSinsResultEntry as _SevenSinsResultEntry, Timestamp as _Timestamp, UserAccount as _UserAccount, UserAccountAdmin as _UserAccountAdmin, UserId as _UserId, UserId__1 as _UserId__1, UserProfile as _UserProfile, UserResultsAdmin as _UserResultsAdmin } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminGetAllAnimalResults(): Promise<{
        __kind__: "ok";
        ok: Array<AnimalResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllAnimalResults();
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllAnimalResults();
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllEmotionResults(): Promise<{
        __kind__: "ok";
        ok: Array<EmotionResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllEmotionResults();
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllEmotionResults();
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllResultCounts(): Promise<{
        __kind__: "ok";
        ok: ResultCounts;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllResultCounts();
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllResultCounts();
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllSevenSinsResults(): Promise<{
        __kind__: "ok";
        ok: Array<SevenSinsResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllSevenSinsResults();
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllSevenSinsResults();
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserResults(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserResultsAdmin;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserResults(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserResults(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimAdmin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAccount(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFeedbackEntry(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedbackEntry(arg0);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedbackEntry(arg0);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<AppAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getAppConfig(): Promise<AdminConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppConfig();
            return result;
        }
    }
    async getDarkSideResult(arg0: string): Promise<{
        __kind__: "ok";
        ok: DarkSideResultSummary | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDarkSideResult(arg0);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDarkSideResult(arg0);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAccount(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserAccount;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAccount(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAccount(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAnimalResults(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<AnimalResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAnimalResults(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAnimalResults(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDarkSideResults(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<DarkSideResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDarkSideResults(arg0);
                return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDarkSideResults(arg0);
            return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEmotionResults(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<EmotionResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmotionResults(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmotionResults(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySevenSinsResults(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<SevenSinsResultEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySevenSinsResults(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySevenSinsResults(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecurityHint(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityHint(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityHint(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecurityQuestion(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityQuestion(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityQuestion(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSecurityQuestionUpdatedAt(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint | null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSecurityQuestionUpdatedAt(arg0);
                return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSecurityQuestionUpdatedAt(arg0);
            return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUsers(): Promise<Array<UserAccountAdmin>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeedback(): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeedback();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: SessionToken;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async resetPasswordWithSecurityQuestion(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordWithSecurityQuestion(arg0, arg1, arg2, arg3);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordWithSecurityQuestion(arg0, arg1, arg2, arg3);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveAnimalResult(arg0: string, arg1: AnimalType, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAnimalResult(arg0, to_candid_AnimalType_n46(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAnimalResult(arg0, to_candid_AnimalType_n46(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDarkSideResult(arg0: string, arg1: Array<DarkSideScore>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDarkSideResult(arg0, to_candid_vec_n49(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDarkSideResult(arg0, to_candid_vec_n49(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDarkSideResultEntry(arg0: string, arg1: string, arg2: number, arg3: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDarkSideResultEntry(arg0, arg1, arg2, arg3);
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDarkSideResultEntry(arg0, arg1, arg2, arg3);
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveEmotionResult(arg0: string, arg1: Array<EmotionScore>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmotionResult(arg0, to_candid_vec_n54(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmotionResult(arg0, to_candid_vec_n54(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveEmotionResultEntry(arg0: string, arg1: string, arg2: number): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmotionResultEntry(arg0, arg1, arg2);
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmotionResultEntry(arg0, arg1, arg2);
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveMyProfile(arg0: AnimalType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMyProfile(to_candid_AnimalType_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMyProfile(to_candid_AnimalType_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveSevenSinsResult(arg0: string, arg1: string, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSevenSinsResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSevenSinsResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDraftMode(arg0: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setDraftMode(arg0);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDraftMode(arg0);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitFeedback(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSecurityQuestion(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSecurityQuestion(arg0, arg1, arg2, arg3);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSecurityQuestion(arg0, arg1, arg2, arg3);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifySecurityQuestion(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifySecurityQuestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifySecurityQuestion(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AnimalResultEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimalResultEntry): AnimalResultEntry {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_AnimalType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimalType): AnimalType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DarkSideResultSummary_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DarkSideResultSummary): DarkSideResultSummary {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DarkSideScore_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DarkSideScore): DarkSideScore {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DarkSideType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DarkSideType): DarkSideType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionResultSummary_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionResultSummary): EmotionResultSummary {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionScore_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionScore): EmotionScore {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionType): EmotionType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccountAdmin_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccountAdmin): UserAccountAdmin {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccount_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccount): UserAccount {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserResultsAdmin_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserResultsAdmin): UserResultsAdmin {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DarkSideResultSummary]): DarkSideResultSummary | null {
    return value.length === 0 ? null : from_candid_DarkSideResultSummary_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnimalType]): AnimalType | null {
    return value.length === 0 ? null : from_candid_AnimalType_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmotionResultSummary]): EmotionResultSummary | null {
    return value.length === 0 ? null : from_candid_EmotionResultSummary_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emotion: Array<_EmotionResultEntry>;
    animal: Array<_AnimalResultEntry>;
    darkSide: Array<_DarkSideResultEntry>;
}): {
    emotion: Array<EmotionResultEntry>;
    animal: Array<AnimalResultEntry>;
    darkSide: Array<DarkSideResultEntry>;
} {
    return {
        emotion: value.emotion,
        animal: from_candid_vec_n2(_uploadFile, _downloadFile, value.animal),
        darkSide: value.darkSide
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topTypes: Array<_DarkSideScore>;
    takenAt: bigint;
}): {
    topTypes: Array<DarkSideScore>;
    takenAt: bigint;
} {
    return {
        topTypes: from_candid_vec_n18(_uploadFile, _downloadFile, value.topTypes),
        takenAt: value.takenAt
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    darkType: _DarkSideType;
    percentage: number;
}): {
    count: bigint;
    darkType: DarkSideType;
    percentage: number;
} {
    return {
        count: value.count,
        darkType: from_candid_DarkSideType_n21(_uploadFile, _downloadFile, value.darkType),
        percentage: value.percentage
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    darkSideResult: [] | [_DarkSideResultSummary];
    gender: string;
    lastLogin: bigint;
    animalArchetype: [] | [_AnimalType];
    securityQuestionUpdatedAt: [] | [bigint];
    emotionResult: [] | [_EmotionResultSummary];
}): {
    id: string;
    age: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    darkSideResult?: DarkSideResultSummary;
    gender: string;
    lastLogin: bigint;
    animalArchetype?: AnimalType;
    securityQuestionUpdatedAt?: bigint;
    emotionResult?: EmotionResultSummary;
} {
    return {
        id: value.id,
        age: value.age,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        darkSideResult: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.darkSideResult)),
        gender: value.gender,
        lastLogin: value.lastLogin,
        animalArchetype: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.animalArchetype)),
        securityQuestionUpdatedAt: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.securityQuestionUpdatedAt)),
        emotionResult: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.emotionResult))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    takenAt: bigint;
    topEmotions: Array<_EmotionScore>;
}): {
    takenAt: bigint;
    topEmotions: Array<EmotionScore>;
} {
    return {
        takenAt: value.takenAt,
        topEmotions: from_candid_vec_n31(_uploadFile, _downloadFile, value.topEmotions)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emotion: _EmotionType;
    count: bigint;
    percentage: number;
}): {
    emotion: EmotionType;
    count: bigint;
    percentage: number;
} {
    return {
        emotion: from_candid_EmotionType_n34(_uploadFile, _downloadFile, value.emotion),
        count: value.count,
        percentage: value.percentage
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId__1;
    takenAt: _Timestamp;
    archetype: _AnimalType;
}): {
    userId: UserId__1;
    takenAt: Timestamp;
    archetype: AnimalType;
} {
    return {
        userId: value.userId,
        takenAt: value.takenAt,
        archetype: from_candid_AnimalType_n5(_uploadFile, _downloadFile, value.archetype)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    createdAt: bigint;
    score: bigint;
    animalType: _AnimalType;
}): {
    id: bigint;
    userId: UserId;
    createdAt: bigint;
    score: bigint;
    animalType: AnimalType;
} {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        score: value.score,
        animalType: from_candid_AnimalType_n5(_uploadFile, _downloadFile, value.animalType)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    age: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    darkSideResult: [] | [_DarkSideResultSummary];
    gender: string;
    passwordHash: string;
    lastLogin: bigint;
    animalArchetype: [] | [_AnimalType];
    emotionResult: [] | [_EmotionResultSummary];
}): {
    id: string;
    age: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    darkSideResult?: DarkSideResultSummary;
    gender: string;
    passwordHash: string;
    lastLogin: bigint;
    animalArchetype?: AnimalType;
    emotionResult?: EmotionResultSummary;
} {
    return {
        id: value.id,
        age: value.age,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        darkSideResult: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.darkSideResult)),
        gender: value.gender,
        passwordHash: value.passwordHash,
        lastLogin: value.lastLogin,
        animalArchetype: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.animalArchetype)),
        emotionResult: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.emotionResult))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AnimalResultEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AnimalResultEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserResultsAdmin;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserResultsAdmin;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserResultsAdmin_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [_DarkSideResultSummary];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DarkSideResultSummary | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Manipulator: null;
} | {
    Sociopath: null;
} | {
    IntrovertedThinker: null;
} | {
    Psychopath: null;
} | {
    ExtravertedThinker: null;
} | {
    ExtravertedFeeler: null;
} | {
    IntrovertedFeeler: null;
}): DarkSideType {
    return "Manipulator" in value ? DarkSideType.Manipulator : "Sociopath" in value ? DarkSideType.Sociopath : "IntrovertedThinker" in value ? DarkSideType.IntrovertedThinker : "Psychopath" in value ? DarkSideType.Psychopath : "ExtravertedThinker" in value ? DarkSideType.ExtravertedThinker : "ExtravertedFeeler" in value ? DarkSideType.ExtravertedFeeler : "IntrovertedFeeler" in value ? DarkSideType.IntrovertedFeeler : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserAccount;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserAccount;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserAccount_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Awe: null;
} | {
    Sadness: null;
} | {
    Fear: null;
} | {
    Guilt: null;
} | {
    Love: null;
} | {
    Peace: null;
} | {
    Desire: null;
} | {
    Anger: null;
} | {
    Happiness: null;
} | {
    Anxiety: null;
}): EmotionType {
    return "Awe" in value ? EmotionType.Awe : "Sadness" in value ? EmotionType.Sadness : "Fear" in value ? EmotionType.Fear : "Guilt" in value ? EmotionType.Guilt : "Love" in value ? EmotionType.Love : "Peace" in value ? EmotionType.Peace : "Desire" in value ? EmotionType.Desire : "Anger" in value ? EmotionType.Anger : "Happiness" in value ? EmotionType.Happiness : "Anxiety" in value ? EmotionType.Anxiety : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_DarkSideResultEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<DarkSideResultEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: [] | [bigint];
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint | null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_opt_n27(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionToken;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Fox: null;
} | {
    Owl: null;
} | {
    Sheep: null;
} | {
    Elephant: null;
} | {
    Bear: null;
} | {
    Lion: null;
} | {
    Wolf: null;
} | {
    Shepherd: null;
} | {
    GoldenRetriever: null;
} | {
    Otter: null;
} | {
    Beaver: null;
} | {
    Dolphin: null;
}): AnimalType {
    return "Fox" in value ? AnimalType.Fox : "Owl" in value ? AnimalType.Owl : "Sheep" in value ? AnimalType.Sheep : "Elephant" in value ? AnimalType.Elephant : "Bear" in value ? AnimalType.Bear : "Lion" in value ? AnimalType.Lion : "Wolf" in value ? AnimalType.Wolf : "Shepherd" in value ? AnimalType.Shepherd : "GoldenRetriever" in value ? AnimalType.GoldenRetriever : "Otter" in value ? AnimalType.Otter : "Beaver" in value ? AnimalType.Beaver : "Dolphin" in value ? AnimalType.Dolphin : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_EmotionResultEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<EmotionResultEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ResultCounts;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ResultCounts;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_SevenSinsResultEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<SevenSinsResultEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DarkSideScore>): Array<DarkSideScore> {
    return value.map((x)=>from_candid_DarkSideScore_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnimalResultEntry>): Array<AnimalResultEntry> {
    return value.map((x)=>from_candid_AnimalResultEntry_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmotionScore>): Array<EmotionScore> {
    return value.map((x)=>from_candid_EmotionScore_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserAccountAdmin>): Array<UserAccountAdmin> {
    return value.map((x)=>from_candid_UserAccountAdmin_n43(_uploadFile, _downloadFile, x));
}
function to_candid_AnimalType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnimalType): _AnimalType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_DarkSideScore_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DarkSideScore): _DarkSideScore {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_DarkSideType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DarkSideType): _DarkSideType {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_EmotionScore_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionScore): _EmotionScore {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_EmotionType_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionType): _EmotionType {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    darkType: DarkSideType;
    percentage: number;
}): {
    count: bigint;
    darkType: _DarkSideType;
    percentage: number;
} {
    return {
        count: value.count,
        darkType: to_candid_DarkSideType_n52(_uploadFile, _downloadFile, value.darkType),
        percentage: value.percentage
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emotion: EmotionType;
    count: bigint;
    percentage: number;
}): {
    emotion: _EmotionType;
    count: bigint;
    percentage: number;
} {
    return {
        emotion: to_candid_EmotionType_n57(_uploadFile, _downloadFile, value.emotion),
        count: value.count,
        percentage: value.percentage
    };
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnimalType): {
    Fox: null;
} | {
    Owl: null;
} | {
    Sheep: null;
} | {
    Elephant: null;
} | {
    Bear: null;
} | {
    Lion: null;
} | {
    Wolf: null;
} | {
    Shepherd: null;
} | {
    GoldenRetriever: null;
} | {
    Otter: null;
} | {
    Beaver: null;
} | {
    Dolphin: null;
} {
    return value == AnimalType.Fox ? {
        Fox: null
    } : value == AnimalType.Owl ? {
        Owl: null
    } : value == AnimalType.Sheep ? {
        Sheep: null
    } : value == AnimalType.Elephant ? {
        Elephant: null
    } : value == AnimalType.Bear ? {
        Bear: null
    } : value == AnimalType.Lion ? {
        Lion: null
    } : value == AnimalType.Wolf ? {
        Wolf: null
    } : value == AnimalType.Shepherd ? {
        Shepherd: null
    } : value == AnimalType.GoldenRetriever ? {
        GoldenRetriever: null
    } : value == AnimalType.Otter ? {
        Otter: null
    } : value == AnimalType.Beaver ? {
        Beaver: null
    } : value == AnimalType.Dolphin ? {
        Dolphin: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DarkSideType): {
    Manipulator: null;
} | {
    Sociopath: null;
} | {
    IntrovertedThinker: null;
} | {
    Psychopath: null;
} | {
    ExtravertedThinker: null;
} | {
    ExtravertedFeeler: null;
} | {
    IntrovertedFeeler: null;
} {
    return value == DarkSideType.Manipulator ? {
        Manipulator: null
    } : value == DarkSideType.Sociopath ? {
        Sociopath: null
    } : value == DarkSideType.IntrovertedThinker ? {
        IntrovertedThinker: null
    } : value == DarkSideType.Psychopath ? {
        Psychopath: null
    } : value == DarkSideType.ExtravertedThinker ? {
        ExtravertedThinker: null
    } : value == DarkSideType.ExtravertedFeeler ? {
        ExtravertedFeeler: null
    } : value == DarkSideType.IntrovertedFeeler ? {
        IntrovertedFeeler: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionType): {
    Awe: null;
} | {
    Sadness: null;
} | {
    Fear: null;
} | {
    Guilt: null;
} | {
    Love: null;
} | {
    Peace: null;
} | {
    Desire: null;
} | {
    Anger: null;
} | {
    Happiness: null;
} | {
    Anxiety: null;
} {
    return value == EmotionType.Awe ? {
        Awe: null
    } : value == EmotionType.Sadness ? {
        Sadness: null
    } : value == EmotionType.Fear ? {
        Fear: null
    } : value == EmotionType.Guilt ? {
        Guilt: null
    } : value == EmotionType.Love ? {
        Love: null
    } : value == EmotionType.Peace ? {
        Peace: null
    } : value == EmotionType.Desire ? {
        Desire: null
    } : value == EmotionType.Anger ? {
        Anger: null
    } : value == EmotionType.Happiness ? {
        Happiness: null
    } : value == EmotionType.Anxiety ? {
        Anxiety: null
    } : value;
}
function to_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DarkSideScore>): Array<_DarkSideScore> {
    return value.map((x)=>to_candid_DarkSideScore_n50(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EmotionScore>): Array<_EmotionScore> {
    return value.map((x)=>to_candid_EmotionScore_n55(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
